Add reporting to goose shoot and improve error handling
keep-starknet-strange/gomu-gomu-no-gatling pull request #42
Opened 2024-02-23 11:17 UTC by Angel-Petrov

This PR now makes shoot write to a reporting file, with information like average TPS as well as how long it took for requests to be sent and how many requests failed. This PR also improves error handling so that failed requests are properly recorded instead of panicing the goose user. The PR has been updated with added instructions and the structure of the output.

An example of the report.json output is attached [here](https://github.com/keep-starknet-strange/gomu-gomu-no-gatling/files/14384772/report.json).

2024-02-28 12:18 UTC, apoorvsadana commented on src/actions/goose.rs
> +                        user.set_failure(&tag, &mut metrics, None, None)?;
should we return after this (and other `set_failure` calls below as well)

2024-02-28 12:18 UTC, apoorvsadana commented on README.md
> +- `all_bench_report`: A report over all benchmarks done
can we say it has the same metrics like the `bench es` mentioned below but it's aggregated

2024-02-28 12:18 UTC, apoorvsadana commented on src/actions/mod.rs
> +        whole_report.benches.push(report);
can we abstract this and the above code in one function

2024-02-28 12:18 UTC, apoorvsadana commented on src/metrics.rs
> +                name: "Total Submission Time",
can you add one line descriptions for these in the readme as well

2024-02-28 12:32 UTC, Angel-Petrov commented on src/actions/goose.rs
> +                        user.set_failure(&tag, &mut metrics, None, None)?;
In the current version of goose there is no way for this to return a `Ok` (which makes it being a `Result` redundant too). There isn't really a ideal solution to this, though in the case where the function also returns a `Result<(), Box<TransactionError>>` you can just `return` it instead, which might be more clear. Otherwise you would have to `unwrap_err` and return that as the error type, or do this.

2024-02-28 12:35 UTC, Angel-Petrov commented on README.md
> +- `all_bench_report`: A report over all benchmarks done
It has less metrics then what would be provided with the specific reports, so saying this wouldn't really be true. Though I'll add that it is a subset of the metrics for the others.

2024-02-28 14:22 UTC, Angel-Petrov commented on README.md
> +    - With these being stored as:
Ah, I have clarified this now

2024-03-07 13:34 UTC, EvolveArt requested changes
left few comments

2024-03-07 13:34 UTC, EvolveArt commented on src/actions/goose.rs
> +                // implement the sequencer fallback.
I don't think that's true anymore tho cc @apoorvsadana

2024-03-07 13:34 UTC, EvolveArt commented on src/actions/goose.rs
> +                        return user.set_failure(&tag, &mut metrics, None, None);
```suggestion
                        return user.set_failure(&tag, &mut metrics, None, Some(reason));
```

2024-03-07 13:34 UTC, EvolveArt commented on src/actions/goose.rs
> +                            "Transaction {tx_hash:#064x} has been rejected/reverted: {reason}"
```suggestion
                            "Transaction {tx_hash:#064x} has been rejected/reverted"
```

2024-03-07 13:34 UTC, EvolveArt commented on src/actions/goose.rs
> +                        return user.set_failure(&tag, &mut metrics, None, None);
We can probably extract this logic to its own function as it's done multiple times throughout the code

2024-03-07 13:34 UTC, EvolveArt commented on src/actions/goose.rs
> +                    return user.set_failure(&tag, &mut metrics, None, None);
same here

2024-03-07 13:34 UTC, EvolveArt commented on src/actions/goose.rs
> +pub async fn raw_send_request<T: DeserializeOwned>(
add some rust doc, not easy to understand what's the difference between raw and non-raw

2024-03-07 13:34 UTC, EvolveArt commented on src/actions/mod.rs
> +    let mut whole_report = WholeReport {
`GlobalReport` might be better naming

2024-03-07 13:34 UTC, EvolveArt commented on src/actions/mod.rs
> +    let mut shooter = GatlingShooterSetup::from_config(config.clone()).await?;
do we really need to clone here?

2024-03-07 13:34 UTC, EvolveArt commented on src/actions/mod.rs
> +    name: &'static str,
avoid lifetimes
```suggestion
    name: String,
```

2024-03-07 13:34 UTC, EvolveArt commented on src/metrics.rs
> +/// A benchmark report contains a name and a vector of metric results
fix comment

2024-03-07 13:34 UTC, EvolveArt commented on src/metrics.rs
> +    pub name: &'static str,
avoid lifetimes
```suggestion
    pub name: String,
```

2024-03-07 13:34 UTC, EvolveArt commented on src/metrics.rs
> +        starknet_rpc: &JsonRpcClient<HttpTransport>,
can we have `starknet_rpc` as a static class member instead of passing it as an argument in every method ? Looks like an anti-pattern to me

2024-03-07 13:34 UTC, EvolveArt commented on src/metrics.rs
> +                value: (requests.total_time as f64 / scenario.counter as f64).into(),
extract this into a function as it's used twice here and will be easier to debug in the future

2024-03-07 13:36 UTC, Angel-Petrov commented on src/actions/goose.rs
> +                // Logic copied from starkli and the following comment too
This comment was copied over from another portion of the codebase, so I wouldn't know where it is from

2024-03-07 13:38 UTC, EvolveArt commented on src/actions/goose.rs
> +                // Logic copied from starkli and the following comment too
Looking at the starkli codebase it doesn't seem to exist anymore

2024-03-07 13:43 UTC, Angel-Petrov commented on src/actions/mod.rs
> +    let mut shooter = GatlingShooterSetup::from_config(config.clone()).await?;
Since we use it later it is needed, but things can be moved around

2024-03-07 13:59 UTC, Angel-Petrov commented on src/metrics.rs
> +        starknet_rpc: &JsonRpcClient<HttpTransport>,
How would a `static class member` look like in rust? We could add `Arc<JsonRpcClient<HttpTransport>>` to the struct but in the future for read metrics I don't think we would need starknet rpc, so it would only be used for the write metrics.

2024-03-07 14:33 UTC, Angel-Petrov commented on src/actions/goose.rs
> +                        return user.set_failure(&tag, &mut metrics, None, None);
Extracted repeated format! into simple closure, extracting out .set_failure itself wouldn't be as trivial

2024-03-07 14:37 UTC, EvolveArt commented on src/metrics.rs
> +        starknet_rpc: &JsonRpcClient<HttpTransport>,
Then we should separate it into 2 different structs like `BenchmarkReportWrite` and `BenchmarkReportRead` and have it as a struct member in the write struct

2024-03-07 14:37 UTC, EvolveArt approved these changes

2024-03-07 14:41 UTC, Angel-Petrov commented on src/metrics.rs
> +        starknet_rpc: &JsonRpcClient<HttpTransport>,
I feel a bit mixed on seperating them since that will add extra complexity, but it can definately be done in a later PR when some read benchmarks are added.

2024-03-08 18:37 UTC, tdelabro requested changes

2024-03-08 18:37 UTC, tdelabro commented on src/metrics.rs
> +        starknet_rpc: &JsonRpcClient<HttpTransport>,
I don't have a strong feeling of it being an anti-patern.
It's not too much duplication and we don't know for sure how it can be abstracted for now.
Let's wait a bit and ask again later

2024-03-08 18:37 UTC, tdelabro commented on src/metrics.rs
> +                unit: "milliseconds",
Can you define `milliseconds` as a constant, to avoid repetition and risk of misspelling and inconsistencies?

2024-03-08 18:37 UTC, tdelabro commented on src/metrics.rs
> +                unit: "milliseconds",
You can also declare it as a variant of Enum `MetringUnit` type, and implement `Display` on it. Not required for now. But may come up handy latter on

2024-03-08 18:37 UTC, tdelabro commented on src/utils.rs
>  impl Default for SysInfo {
Is this really something we want?
It won't result in a good display if used. I would prefer an error message than a default value everywhere if we end up in this situation.

2024-03-11 09:32 UTC, Angel-Petrov commented on README.md
> +  - `location`: Path to the file where to save the reports
It has been replaced with a file yes and it'll overwrite with each run

2024-03-15 14:30 UTC, EvolveArt commented on src/actions/goose.rs
> +                // implement the sequencer fallback.
please update comment @Angel-Petrov

2024-03-18 22:01 UTC, tdelabro approved these changes

2024-03-18 22:01 UTC, merged