[Feat]: support contracts compiled with version 2.1.0
keep-starknet-strange/gomu-gomu-no-gatling pull request #5
Opened 2023-09-12 17:58 UTC by haroune-mohammedi

Contracts compiled from https://github.com/OpenZeppelin/cairo-contracts commit 83076441b0d7b965f9c533c774f5c3d7b39381cd

With some changes to keep the same function parameters with v0 contracts

```
diff --git a/Scarb.toml b/Scarb.toml
index bf42b24..7694e0d 100644
--- a/Scarb.toml
+++ b/Scarb.toml
@@ -18,4 +18,4 @@ starknet = ">=2.1.0-rc0"
 [[target.starknet-contract]]
 allowed-libfuncs-list.name = "experimental"
 sierra = true
-casm = false
+casm = true
diff --git a/src/token/erc20/erc20.cairo b/src/token/erc20/erc20.cairo
index 9448b8e..e6bc054 100644
--- a/src/token/erc20/erc20.cairo
+++ b/src/token/erc20/erc20.cairo
@@ -45,6 +45,7 @@ mod ERC20 {
         ref self: ContractState,
         name: felt252,
         symbol: felt252,
+        decimals: felt252,
         initial_supply: u256,
         recipient: ContractAddress
     ) {
diff --git a/src/token/erc721/erc721.cairo b/src/token/erc721/erc721.cairo
index 32a265c..e042f31 100644
--- a/src/token/erc721/erc721.cairo
+++ b/src/token/erc721/erc721.cairo
@@ -66,10 +66,10 @@ mod ERC721 {
         name: felt252,
         symbol: felt252,
         recipient: ContractAddress,
-        token_id: u256
+        // token_id: u256
     ) {
         self.initializer(name, symbol);
-        self._mint(recipient, token_id);
+        // self._mint(recipient, token_id);
     }

     //
@@ -364,4 +364,10 @@ mod ERC721 {
             DualCaseSRC5 { contract_address: to }.supports_interface(account::interface::ISRC6_ID)
         }
     }
+
+    #[external(v0)]
+    fn mint(ref self: ContractState, to: ContractAddress, token_id: u256) -> bool {
+        self._mint(to, token_id);
+        true
+    }
 }
 ```

2023-09-12 20:14 UTC, d-roak commented on src/actions/shoot.rs
> +                panic!("Could not declare contract: {e}");
shouldn't this be removed?

2023-09-12 20:14 UTC, d-roak commented on src/actions/shoot.rs
>                  panic!("Could not declare contract: {e}");
Same as the other one

2023-09-12 21:55 UTC, haroune-mohammedi commented on src/actions/shoot.rs
> +                panic!("Could not declare contract: {e}");
Done

2023-09-12 21:55 UTC, haroune-mohammedi commented on src/actions/shoot.rs
>                  panic!("Could not declare contract: {e}");
Done

2023-09-13 09:37 UTC, tdelabro requested changes

2023-09-13 09:37 UTC, tdelabro commented on src/actions/shoot.rs
> +        let flattened_class = contract_artifact.flatten().unwrap();
Explain why it is ok to unwrap in a comment

2023-09-13 11:09 UTC, haroune-mohammedi commented on src/actions/shoot.rs
> +            ExecutionEncoding::Legacy,
Updated comment

2023-09-13 11:09 UTC, haroune-mohammedi commented on src/actions/shoot.rs
> +        let flattened_class = contract_artifact.flatten().unwrap();
Replaced with ? operator

2023-09-13 11:39 UTC, tdelabro commented on src/actions/shoot.rs
> +            ExecutionEncoding::Legacy,
But you also have to make it configurable. So one or the other is used depending of the type of contracts you want to deploy. No?

2023-09-13 12:47 UTC, tdelabro approved these changes

2023-09-13 14:11 UTC, merged